name: "Create release"
description: "create a release when commit is pushed to master/main" 
inputs:
  REPO_NAME:
    description: "The name of the repo: user/repo_name"
    required: false
    default: ''
  ACCESS_TOKEN:
    description: "Github Access Token you want to use. Just pass GITHUB_TOKEN"
    required: true
  BRANCH:
    description: "The branch to update file specified in PATH"
    required: false
    default: ''
  PULL_REQUEST:
    description: "Open a new pull request if set to a target branch name"
    required: false
    default: ''
  COMMIT_MESSAGE:
    description: "Commit message"
    required: false
    default: 'docs(CHANGELOG): update release notes'
  TYPE:
    description: "The type of commits you want to add to CHANGELOG"
    required: false
    default: 'feat:Feature,fix:Fix'
  COMMITTER:
    description: "The name and email of the committer. e.g. 'author <author@example.com>'"
    required: false
    default: ''
runs:
  using: "docker"
  image: "Dockerfile"