name: Create New Release
on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # - uses: BobAnkh/auto-generate-changelog@masters
    - uses: rp-01/react-query-starwars/.github/actions/create-release@main
      with:
        REPO_NAME: ''
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
        TYPE: 'feat,fix,breaking change,docs,refactor,perf'
        BRANCH: "main"
# test pull requestsgit 
# in branch ss-10
# in branch ss-3
# in main branch